/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.0.0
 */

export interface AppDtoWordWord {
  createdAt: string;
  id: number;
  isChecked: boolean;
  updatedAt: string;
  word: string;
}
