/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.0.0
 */

export interface BodyLoginUserLoginPost {
  client_id?: string;
  client_secret?: string;
  grant_type?: string;
  password: string;
  scope?: string;
  username: string;
}
