/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { WordFilterTypes } from './wordFilterTypes';

export type GetWordsWordAllGetParams = {
page?: number;
limit?: number;
type?: WordFilterTypes;
};
