/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 1.0.0
 */
import type { AppDtoWordWord } from './appDtoWordWord';

export interface PaginatedWord {
  pages: number;
  total_items: number;
  words: AppDtoWordWord[];
}
