/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Badword API
 * The badword API
 * OpenAPI spec version: 1.0
 */

export interface Word {
  createdAt: string;
  id: string;
  isChecked: boolean;
  updatedAt: string;
  word: string;
}
